# Generated by Django 3.2.6 on 2021-09-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_auto_20210920_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproducts',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록날짜'),
        ),
        migrations.AlterField(
            model_name='tproducts',
            name='tname',
            field=models.CharField(max_length=50, unique=True, verbose_name='여행상품'),
        ),
    ]
