# Generated by Django 3.2.6 on 2021-09-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_auto_20210920_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproducts',
            name='tname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='여행상품'),
        ),
    ]
