# Generated by Django 3.2.7 on 2021-09-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0019_mome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mome',
            new_name='Memo',
        ),
    ]
