# Generated by Django 3.2.7 on 2021-09-29 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0022_rename_img_memo_t_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tproducts',
            name='t_userid',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='아이디\x1d'),
            preserve_default=False,
        ),
    ]
