# Generated by Django 3.2.7 on 2021-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0023_tproducts_t_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproducts',
            name='tname',
            field=models.CharField(max_length=50, verbose_name='여행상품'),
        ),
    ]
