# Generated by Django 3.2.6 on 2021-09-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_tproducts_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproducts',
            name='tname',
            field=models.CharField(max_length=50, null=True, verbose_name='여행상품'),
        ),
    ]
