# Generated by Django 3.2.6 on 2021-09-20 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20210920_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproducts',
            name='s_trip1',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='출발날짜'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tproducts',
            name='s_trip2',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='도착날짜'),
            preserve_default=False,
        ),
    ]
