# Generated by Django 3.2.6 on 2021-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20210920_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproducts',
            name='s_trip1',
            field=models.DateField(null=True, verbose_name='출발날짜'),
        ),
        migrations.AlterField(
            model_name='tproducts',
            name='s_trip2',
            field=models.DateField(null=True, verbose_name='도착날짜'),
        ),
    ]
