# Generated by Django 3.2.6 on 2021-09-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_auto_20210920_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproducts',
            name='count',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True, verbose_name='인원수'),
        ),
        migrations.AlterField(
            model_name='tproducts',
            name='country',
            field=models.CharField(choices=[('eng', '영국'), ('spa', '스페인'), ('net', '네덜란드'), ('ran', '프랑스'), ('ita', '이탈리아'), ('swi', '스위스'), ('cze', '체코'), ('tur', '터키'), ('hon', '홍콩'), ('thi', '태국')], max_length=3, null=True, verbose_name='여행국가'),
        ),
    ]
