# Generated by Django 3.2.6 on 2021-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_auto_20210920_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproducts',
            name='tname',
            field=models.CharField(max_length=50, unique=True, verbose_name='여행상품'),
        ),
    ]
