# Generated by Django 3.2.7 on 2021-09-24 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_alter_tproducts_tname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproducts',
            name='count',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=django.utils.timezone.now, max_length=1, verbose_name='인원수'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tproducts',
            name='country',
            field=models.CharField(choices=[('eng', '영국'), ('spa', '스페인'), ('net', '네덜란드'), ('ran', '프랑스'), ('ita', '이탈리아'), ('swi', '스위스'), ('cze', '체코'), ('tur', '터키'), ('hon', '홍콩'), ('thi', '태국')], default=django.utils.timezone.now, max_length=3, verbose_name='여행국가'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tproducts',
            name='s_trip1',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='출발날짜'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tproducts',
            name='s_trip2',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='도착날짜'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tproducts',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록날짜'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tproducts',
            name='tname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='여행상품'),
            preserve_default=False,
        ),
    ]
