# Generated by Django 3.2.7 on 2021-09-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0017_alter_tproducts_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_and_T',
            fields=[
                ('idid', models.AutoField(primary_key=True, serialize=False)),
                ('T_id', models.ForeignKey(db_column='Tproducts', on_delete=django.db.models.deletion.CASCADE, related_name='Tproducts', to='trip.tproducts')),
                ('U_id', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, related_name='User', to='trip.user')),
            ],
        ),
    ]
