# Generated by Django 3.2.7 on 2021-09-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0018_user_and_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
