# Generated by Django 3.2.7 on 2021-09-25 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0020_rename_mome_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='b_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='사용자명'),
            preserve_default=False,
        ),
    ]
