# Generated by Django 3.2.7 on 2021-09-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0021_memo_b_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='img',
            new_name='t_img',
        ),
    ]
